version: '3'
services:
  mysql:
    image: mysql:5
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: akaunting_root_password
      MYSQL_DATABASE: ${DB_PREFIX}${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  web:
    image: akaunting
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    environment:
      APP_DEBUG: "true"
    links:
      - mysql
